# Generated by Django 5.2.8 on 2025-11-26 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное имя автора (например: Лев Толстой)', max_length=150, unique=True, verbose_name='Имя автора')),
                ('biography', models.TextField(blank=True, help_text='Краткая биография или описание автора', verbose_name='Биография')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('death_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год смерти')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название книги')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('publisher', models.CharField(max_length=100, verbose_name='Издательство')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка книги')),
                ('file', models.FileField(upload_to='books/', verbose_name='Файл книги (PDF, EPUB и т.д.)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title', 'year'],
                'constraints': [models.UniqueConstraint(fields=('title', 'author', 'year', 'publisher'), name='unique_book_edition')],
            },
        ),
    ]
