# Generated by Django 5.2.8 on 2025-11-26 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='ФИО Автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000, message='Год должен быть не меньше 1000'), django.core.validators.MaxValueValidator(9999, message='Год должен быть не больше 9999')], verbose_name='Год выпуска'),
        ),
    ]
