# Generated by Django 5.2.8 on 2025-11-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_biography_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='books/', verbose_name='Файл книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Художественная литература'), ('fantasy', 'Фантастика'), ('sci_fi', 'Научная фантастика'), ('detective', 'Детектив'), ('romance', 'Романтика'), ('horror', 'Ужасы'), ('history', 'История'), ('biography', 'Биография'), ('education', 'Учебная литература'), ('poetry', 'Поэзия'), ('drama', 'Драма'), ('other', 'Другое')], max_length=20, verbose_name='Жанр книги'),
        ),
    ]
